version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: cloudflared_server_1
      APP_PORT: 8080

  server:
    container_name: cloudflaretunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=secret
    command: tunnel --no-autoupdate run
