version: '3.9'

services:
  server:
    container_name: cloudflaretunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=secret
    command: tunnel --no-autoupdate run
