version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: flaresolverr_server_1
      APP_PORT: 8191
      PROXY_AUTH_WHITELIST: "*"

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
